# Generated by Django 5.2.1 on 2025-06-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinterview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEntries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('experience_level', models.CharField(max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('industry', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('position_type', models.CharField(max_length=50)),
                ('certifications', models.JSONField(default=list)),
                ('preferred_technologies', models.JSONField(default=list)),
                ('soft_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Entries',
                'db_table': 'interview_entries',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('question_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinterview.interviewentries')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['question_order'],
            },
        ),
    ]
