# Generated by Django 5.2.1 on 2025-06-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinterview', '0002_interviewentries_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_score', models.FloatField()),
                ('feedback', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('question_scores', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_entries', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vinterview.interviewentries')),
            ],
            options={
                'db_table': 'interview_results',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview_entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinterview.interviewentries')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinterview.question')),
            ],
            options={
                'db_table': 'answers',
                'unique_together': {('question', 'interview_entries')},
            },
        ),
    ]
