# Generated by Django 5.2.12 on 2026-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinterview', '0003_interviewresult_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewentries',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
